### ISSUE TITLE
建议开放源代码

### ISSUE THREAD

**Issue by zhangkui-china** [zhengpengfeichn/VxTerm#3]
鹏飞，这个是远程操作类软件，有一定敏感性，下载的Exe文件360直接报病毒木马，建议您开放源代码，这样一方面便于大家检查是否存在安全隐患，另一方面也可众人拾柴火焰高，共同促进和完善软件。谢谢。

**Comment by zhengpengfeichn** [comment]
不可能报病毒吧？我提交给360做过检测，是可以通过的。而且我没有用任何有关于脚本/宏执行的模块。
我这边测试是没有的。并且我已经把早前一个版本提交给360开放平台做过检测，是可以检测通过的。


360杀毒扫描日志

病毒库日期：2023-05-17
扫描时间：2023-05-24 11:15:22
扫描用时：00:00:01
扫描类型：右键扫描
扫描文件总数：1
项目总数：0
清除项目数：0

扫描选项
----------------------
扫描所有文件：否
扫描压缩包：否
发现病毒处理方式：由用户选择处理
扫描磁盘引导区：是
扫描 Rootkit：否
使用云查杀引擎：是
使用QVM人工智能引擎：是
扫描建议修复项：是
常规引擎设置：未使用

扫描内容
----------------------
C:\temp\VxTerm.exe

**Comment by zhengpengfeichn** [comment]
不可能报病毒吧？我提交给360做过检测，是可以通过的。而且我没有用任何有关于脚本/宏执行的模块。
我这边测试是没有的。并且我已经把早前一个版本提交给360开放平台做过检测，是可以检测通过的。


360杀毒扫描日志

病毒库日期：2023-05-17
扫描时间：2023-05-24 11:15:22
扫描用时：00:00:01
扫描类型：右键扫描
扫描文件总数：1
项目总数：0
清除项目数：0

扫描选项
----------------------
扫描所有文件：否
扫描压缩包：否
发现病毒处理方式：由用户选择处理
扫描磁盘引导区：是
扫描 Rootkit：否
使用云查杀引擎：是
使用QVM人工智能引擎：是
扫描建议修复项：是
常规引擎设置：未使用

扫描内容
----------------------
C:\temp\VxTerm.exe



扫描结果
======================
未发现威胁文件
-------------------------
关于您的建议开放源代码，我本人是会考虑的，只是现在我暂时没法把源代码进行格式及做相关的优化，不太适合于做开放。我期待于我把其中的所有的功能都按照我的想法都实现了过后，再来考虑关于开放源代码的计划。
目前只是想把产品先开放出来，接受市场的考验，获得有效的反馈信息，进行优化。

**Comment by zhengpengfeichn** [comment]
不可能报病毒吧？我提交给360做过检测，是可以通过的。而且我没有用任何有关于脚本/宏执行的模块。
我这边测试是没有的。并且我已经把早前一个版本提交给360开放平台做过检测，是可以检测通过的。


360杀毒扫描日志

病毒库日期：2023-05-17
扫描时间：2023-05-24 11:15:22
扫描用时：00:00:01
扫描类型：右键扫描
扫描文件总数：1
项目总数：0
清除项目数：0

扫描选项
----------------------
扫描所有文件：否
扫描压缩包：否
发现病毒处理方式：由用户选择处理
扫描磁盘引导区：是
扫描 Rootkit：否
使用云查杀引擎：是
使用QVM人工智能引擎：是
扫描建议修复项：是
常规引擎设置：未使用

扫描内容
----------------------
C:\temp\VxTerm.exe

-------------------------
关于您的建议开放源代码，我本人是会考虑的，只是现在我暂时没法把源代码进行格式及做相关的优化，不太适合于做开放。我期待于我把其中的所有的功能都按照我的想法都实现了过后，再来考虑关于开放源代码的计划。
目前只是想把产品先开放出来，接受市场的考验，获得有效的反馈信息，进行优化。
