### ISSUE TITLE
提示有病毒

### ISSUE THREAD

**Issue by justinyx** [zhengpengfeichn/VxTerm#4]

**Comment by zhengpengfeichn** [comment]
不可能报病毒吧？我提交给360做过检测，是可以通过的。而且我没有用任何有关于脚本/宏执行的模块。
我这边测试是没有的。并且我已经把早前一个版本提交给360开放平台做过检测，是可以检测通过的。


360杀毒扫描日志

病毒库日期：2023-05-17
扫描时间：2023-05-24 11:15:22
扫描用时：00:00:01
扫描类型：右键扫描
扫描文件总数：1
项目总数：0
清除项目数：0

扫描选项
----------------------
扫描所有文件：否
扫描压缩包：否
发现病毒处理方式：由用户选择处理
扫描磁盘引导区：是
扫描 Rootkit：否
使用云查杀引擎：是
使用QVM人工智能引擎：是
扫描建议修复项：是
常规引擎设置：未使用

扫描内容
----------------------
C:\temp\VxTerm.exe



扫描结果
======================
未发现威胁文件
